
using Microsoft.Extensions.Configuration;
using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Transactions;
namespace LicenseManager.TestAPIs
{
    [TestClass]
    public class BaseTest
    {
        static BaseTest()
        {

        }

        [TestInitialize]
        public virtual void Init()
        {

            // Inizializzare EF per SQL Server
            //EVLogCore.Entity.SqlClient.BootStrapper.Initialize();
        }

        protected static string TokenAccess { get => $"NmV0d3ExaXpzVVZrSFJYRVhwdFBmYlBQYkwyQjdSYXR0REI4TDJOOVFVczVjNk44WUJkVS9vbUZXTGNWZDhwakU4T2ozeW1pUDhJYnZrNUlGakg2SXdSejA0Q2RBM2JxaXpaSlZXUjdUdTJYQ2doU2FqWkdmZk5vcjlpT3dEY2FTbUIzU0JyMGxWdWdXS1ZUVSt6TGJPMDNOeExZbE5vTWczMGZOeTRvVnR2bnRiYU5MWkZtK0VpUXpQR1A5Wm85N01Xa3F4VnVhcVFlU1NTSUVnUXA2U1lVUGNRTk1XUHROU0VLWDBlMVJoNStUL2FvdFdkb1UxMDNlMnQ3SzdabVpoMUc2NXltdGZxdWhwcFNPUHFjRmVSK3dqSkhscmp5Y283TUlBMW1ZMGZ1KzhTMC84TGNZdEtwdTZ1aDZvUDdQaTc5cWViTUVrbHhzd3UzaWd3ZUhTTmdMS1Mwand6NFZjanplR210cHFqMWtaek9QZHFJNndtc3J0RkxaS0NGaHJNZ2JYYVJzNFJKNWFySDQwYUNoOTNmL0djZ0JZT3lHL0NxV1pCUnBnUzV3QXFyNjMvNEJkZkhlaS9wUnlrZnI3cWxOdHNOZERNc2o0c09JQ1B1STBRSVphcHFVdmptZ015QjR4akxnWGFKeWcrYTZGbWM2ZHV6UEwvejJsL2tRd29mci8zYS9hQXJGQUxqOU9yMmtuckJjZDJrZEFoa3R5eHBBVW93b2E0YTZLc3lHL0V2L014bytiYmJxOUhHdm45Ly9hOUZWRlFBbFUrNkVhQVJwSWVSTDkzeEdLUStWWGNhNktITng0MjRTREtWL3cvUkZqMFpORmFSTWNTbkhQUjhSN3hqKzY5WmFTOXIvK2oxOGErRnpQODlkUVJ1d2RZK1VaVjUwTHozSzlPMG5DVWxxVFRndERDSGhhTkFYZ3hLS2dJT3JseWI0Z09XWGx2YStNb1Z1Ym9uK1Z3OWU2N2pESUprNndhaGY1UEpYeDVBYlIwNVF0eUs5cm5RcGZNWnJTVjdqRjAyMUFSUVlGY0ZGZzdaWVYzYWhyWmlKcEY0TWUvMXdyYlJXVmN4VEVnQXQ3ZlFFSXFHMlVjOXo2YnV5ZVVZbytzY0dITWIwVjNqQ3FtaTdnV2hrRXI3VlJqeEZUVHBMNkRjdk4zM2t1K0FEV2tuUzV3WjNOV2daZW1acVpZWlp5U3NGY0V0RVdSdVdKekZ2WlZvOStPZTJPVzhOV2pZaTVBL2xxMUsyYWtrbHBQa1hPekdvUGtXQnVWVXd4bm9tLzJOdWhXaW1Uek9GL0xDU2dWK2hLdzZwcW0vMC9KTW1LQ0tEZFFEa2NWL3VTcklTTzBSQld6ZjhiZlpHaURIdnpud2RiVGRKZTA0VDBUQXBVc29mQkFOVTBqS2pEdlR2TW9kVlFzQzRkcjlKQmVrQzlwTk9nNkpYSVBLbXNOY2x6aXFPaldSalEvMU5yc1ZwWEVpK3p1VS8zeDFJbnBtNVVXNkdUTW9YamxZZ0JzTk51WnRhM2lZZmtrWEVrRG9EODBsdVBHMmo1OGhObkpOMmtkQ2VWVnB1WXZtTHJZM3F5VjNSbWsrRklYOFE3TTA5bFVWT1ZBU1lycGI2MC9GMlBqVDVnUzVVQ0dUNUNBa093d0dkV1dIaE9SZ3RzWnVuRHNzelNWWU1UU2w2UFlmSi9FUjVuQXpNUUYxZjlqTkxObWc3Z0M4SXlYSEpYZlRzTlZESTYyOFhiODZkMTZPMkxBc3NVUGF2VXhCK2FJYUp3Vkc5QVhsYUNxS0VYaVYzdWFwbE1lcjRuSG1wRjV2U0JPVEowWGdoWHZrbjV0OXFqd28zS2loMjNJUHkzbEFBcnBiWVhGVnNLbXpmNFh3SmJHTFBRMExIQUNrdGFoM3UxTEhUZjRoaFp6QTFkNWFUS2JPS2RPUUc2WFQybndBemhBWmYrV3lzSng5ZExRNWFUWFFTZFBZc2gvNDNSK1Q5ajNTcTlxV1hNOHVsSEtJR3M2aEg2VWdoZWE0WFF4b00vRzRLWFVSM2JlSG5Tc1lQT3FwdjlheG9kdW1WU25UTmEwS1RHR012bTJJcllwU2tONC9HeFZwckt2WUpvZStUWkZScUx0QnBQejJxMUJETkxzYStNRWtyWmpBRjduYi81eCtKT2dsVnVMQVBUWk1INm5MWlZQYlhFR0VTeUp1WXNVYXR5dUVyMU14TTc0TEE1L0Z0cnBycEt4cXhscVNndHdGNWpTQWlFemtRNkFUK0I0dTg2UDk3SXZhcVp2ZGlSZWZZdlI1QlF4UUlLazAzdWJuMlhEMTNwcWY0bFZBU0pBU3AwVkRhY0xlaDh3aTJPTkFmV29FVmNhTUl5RWhIajFHK0lCNjhRVVpldUxQS0k0UkVybFU4eGFiYld5NW9JdFJWd2R6ejF6T09mMGdPOWtaMDNlWkdGWkMrZWtVd050dEphdytHdnVHcFJpWjk3L01vSjlQM2VqZ0F0Tk1Oa0xYdHBmcWZuVnhIM2JITzlzSDB6UmVKaFZ1Q1N6N2EzZ1JLTzNweXNJb1FFdjdsdEZ5VG1LOGM2YnBOWkY1eEhNNFQ1U003ZHZwRE9vZUZ5Y0RlQkU2djdzeHVnVXJ2VC8vOTRGUU5qY0k4Vm8zTWNNNXl0QVQvbGx1OHJmWmxlcXk2TExyYnFFY2FKem5iQUlSZW9iSUZQTlBiR3c5VUJ2UzZGOTYwek9XcTkwZ1RxN2ZZSjR4RG4xQ3dUajZHdDh6a2hsSFd5NE05aHdtSW9pZ3pEVHFhM2t6RmZydnVLYzNLb094aTlNVUM3OERkdnNxS0d3dTZobjY0UnMyZ1QxRU1xVW9UOElGU0R3cmh5QzNVdWhFSDlwZ2pJVUVaTEVoMVJKM2tUNFhnV0FpNjVmSVBlWThMbHh0YzExS0FJb29BaTFNeDYrWDExRmlQUjIyYUZhTmNKSWNqQTJXenFoeGNYWjBtSmpKU0JmMzJxbWJoUTlwa2p5WWFNcXZrN2hUVWZNMXMySnByR2RmSStvUlhIb051WVNiYUJvZDV1L2wvUk1WWC9BRXprVStabHJ2SGMxZk5JOEZFcWpPWjFEQ2F0U2JnUUdtekdVY3d0TDJVMnNycmxqaEpHd25PbURrWkQrekZFYzIvSUFnVTl6RE5TN0FWSFdPeGc9PQ=="; }

        protected static void DoSQLTestThrowException(
            Action action
        )
        {
            using TransactionScope transactionScope = new();
            try
            {
                action();
            }
            catch (Exception ex)
            {
                //ok = false;
                Console.WriteLine(ex.Message);
                throw;
            }
            finally
            {
                transactionScope.Dispose();
            }
        }


    }
}
